makewiki/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import SignUpView
"""
CHALLENGES:
    1. Uncomment the path() for the wiki app below. Use it to direct any request (except `/admin` URLs)
        to the the `wiki` app's URL configuration. Use the above docstring to guide you if you feel stuck.
    2. Make sure Django doesn't give you any warnings or errors when you execute `python manage.py runserver`.
"""
urlpatterns = [
    # Admin Site
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', SignUpView.as_view(), name = 'signup'),


    # Wiki App
    path('', include('wiki.urls')),
]

wiki/urls.py
from django.urls import path
from wiki.views import PageListView, PageDetailView, PageCreateView

app_name = 'wiki'
urlpatterns = [
    path('', PageListView.as_view(), name='wiki-list-page'),
    path('newpage/', PageCreateView.as_view(), name = 'page-create-view'),
    path('<str:slug>', PageDetailView.as_view(), name='wiki-details-page'),
]

accounts/models.py
from django.db import models

# Create your models here.

api/models.py
from django.db import models

# Create your models here.

wiki/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse, reverse_lazy
from django.utils.text import slugify
from django.utils import timezone
from django.contrib.auth.models import User


class Page(models.Model):
    """ Represents a single wiki page. """
    title = models.CharField(max_length=settings.WIKI_PAGE_TITLE_MAX_LENGTH, unique=True,
                             help_text="Title of your page.")
    author = models.ForeignKey(User, on_delete=models.PROTECT,
                               help_text="The user that posted this article.")
    slug = models.CharField(max_length=settings.WIKI_PAGE_TITLE_MAX_LENGTH, blank=True, editable=False,
                            help_text="Unique URL path to access this page. Generated by the system.")
    content = models.TextField(
        help_text="Write the content of your page here.")
    created = models.DateTimeField(auto_now_add=True,
                                   help_text="The date and time this page was created. Automatically generated when the model saves.")
    modified = models.DateTimeField(auto_now=True,
                                    help_text="The date and time this page was updated. Automatically generated when the model updates.")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """ Returns a fully-qualified path for a page (/my-new-wiki-page). """
        path_components = {'slug': self.slug}
        return reverse('wiki-details-page', kwargs=path_components)

    def save(self, *args, **kwargs):
        """ Creates a URL safe slug automatically when a new a page is created. """
        if not self.pk:
            self.slug = slugify(self.title, allow_unicode=True)

        # Call save on the superclass.
        return super(Page, self).save(*args, **kwargs)

wiki/forms.py
from django import forms
from wiki.models import Page


class PageForm(forms.ModelForm):
    """ Render and process a form based on the Page model. """
    class Meta:
        fields = ['author', 'title', 'content']
        model = Page

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

# Create your views here.

api/views.py
from django.shortcuts import render

# Create your views here.

wiki/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from wiki.models import Page
from wiki.forms import PageForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy



class PageListView(ListView):
  """ Renders a list of all Pages. """
  model = Page

  def get(self, request):
      """ GET a list of Pages. """
      pages = self.get_queryset().all()
      return render(request, 'list.html', {
        'pages': pages
      })

class PageDetailView(DetailView):
  """ Renders a specific page based on it's slug."""
  model = Page

  def get(self, request, slug):
      """ Returns a specific wiki page by slug. """
      page = self.get_queryset().get(slug__iexact=slug)
      return render(request, 'page.html', {
        'page': page
      })

class PageCreateView(CreateView):
  
  
  def get(self, request):
    context = {'form':PageForm(request.POST)}
    return render(request, 'new_page.html', context)


  def post(self, request, *args, **kwargs):
    form = PageForm(request.POST)
    if form.is_valid():
      new_wiki_page = form.save()
      return HttpResponseRedirect(reverse_lazy('wiki:wiki-details-page', args=[new_wiki_page.slug]))
    return render(request, 'new_page.html', {'form':form})

  #   if request.method == "POST":
  #     form = PageForm(request.POST)
  #     print("_____ form ___________")

  #     print(request.POST.get('slug', ''))


  #     if form.is_valid():
  #       wiki.title  = request.POST.get('title', '')
  #       wiki.slug = request.POST.get('slug', '')
  #       wiki.content = request.POST.get('content', '')
  #       wiki.modified = request.POST.get('modified', '')
  #       wiki.created = request.POST.get('created', '')
  #       wiki.author = User.objects.get(id=request.user.id)
  #       wiki.save()
      
  #       return HttpResponseRedirect(reverse('wiki:wiki-details-page', kwargs={'slug': wiki.slug}))


  #     else:

  #         errors = " Wiki was not updated"
  #         # messages.error(request, errors, extra_tags='alert')
  #         print("________________")
  #         print(errors)
  #   else:
  #       form = PageForm(instance=wiki)
  #       print("________________")
  #       print("Not a post request")
      
    
  #   wiki = Page()

  #   context = {'wiki_pages_detail': wiki,'form': form}

  #   return render(request, 'new_page.html', context)

  

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/e7c15fdb77.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>makewiki</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'wiki:wiki-list-page' %}"><i class="fas fa-fw fa-book"></i> makewiki</a>
      <form class="form-inline ml-auto">
        <div class="text-white">Hello, <strong>{{ user }}</strong>!</div>
        {% if user.is_authenticated %}
        <a href="{% url 'wiki:page-create-view' %}" class="btn btn-success ml-4">New Page</a>
        <a href="{% url 'logout' %}" class="btn btn-danger ml-2">Log Out</a>
        {% else %}
        <a href="{% url 'login' %}" class="btn btn-secondary ml-2">Log In</a>
        <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign Up</a>
        {% endif %}
      </form>
    </nav>
    <main role="main" class="container" style="margin-top: 4vh;">
      {% block content %}
        <div class="row">
          <div class="col m-4">
            <div class="alert alert-warning" role="alert">
              If you see this, you forgot <code>{% verbatim %}{% block content %}{% endblock %}{% endverbatim %}</code> in your child template.
            </div>
          </div>
        </div>
      {% endblock %}
    </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>
  </body>

wiki/templates/list.html
{% extends "base.html" %}

{% block content %}
  <h3>Wikis {% if pages %}<small class="text-muted">({{ pages|length }} Page{{ pages|length|pluralize:"s" }})</small>{% endif %}</h3>
  <hr>
  {% if pages %}
    <div class="card-columns">
      {% for page in pages %}
        {% include "partials/card.html" %}
      {% endfor %}
    </div>
  {% else %}
    <div class="alert alert-primary" role="alert">No pages to display.</div>
  {% endif %}
{% endblock %}

wiki/templates/new_page.html
{% extends "base.html" %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>
{% endblock %}

wiki/templates/page.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col m-4">
      <h3>{{ page.title }} <small class="text-muted">Last updated {{ page.modified|date:"SHORT_DATETIME_FORMAT" }} by <b>{{ page.author.username }}</b></small></h3>
      <hr>
      <p>{{ page.content|linebreaksbr }}</p>
      <hr>
      <a href="{% url 'wiki:wiki-list-page' %}">Back to List</a>
    </div>
  </div>
{% endblock %}

wiki/templates/partials/card.html
<div class="card mb-3">
  <h5 class="card-header ">{{ page.title }}</h5>
  <div class="card-body border-dark">
    <p class="card-text text-dark">
      {{ page.content|truncatewords_html:30 }}
      <hr>
      <div class="text-right"><a href="{% url 'wiki:wiki-details-page' page.slug %}" title="Read More">Read More</a></div>
  </div>
  <div class="card-footer">
    <small class="text-muted">Last updated {{ page.modified|date:"SHORT_DATETIME_FORMAT" }} by <b>{{ page.author.username }}</b></small>
  </div>
</div>